add_test( TTopologyTest.AddNode /workspaces/labs_os-1/bin/lab5-7_test [==[--gtest_filter=TTopologyTest.AddNode]==] --gtest_also_run_disabled_tests)
set_tests_properties( TTopologyTest.AddNode PROPERTIES WORKING_DIRECTORY /workspaces/labs_os-1/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TTopologyTest.AddDuplicateNode /workspaces/labs_os-1/bin/lab5-7_test [==[--gtest_filter=TTopologyTest.AddDuplicateNode]==] --gtest_also_run_disabled_tests)
set_tests_properties( TTopologyTest.AddDuplicateNode PROPERTIES WORKING_DIRECTORY /workspaces/labs_os-1/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TTopologyTest.RemoveNode /workspaces/labs_os-1/bin/lab5-7_test [==[--gtest_filter=TTopologyTest.RemoveNode]==] --gtest_also_run_disabled_tests)
set_tests_properties( TTopologyTest.RemoveNode PROPERTIES WORKING_DIRECTORY /workspaces/labs_os-1/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TTopologyTest.GetChildren /workspaces/labs_os-1/bin/lab5-7_test [==[--gtest_filter=TTopologyTest.GetChildren]==] --gtest_also_run_disabled_tests)
set_tests_properties( TTopologyTest.GetChildren PROPERTIES WORKING_DIRECTORY /workspaces/labs_os-1/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TSumTest.SimpleSum /workspaces/labs_os-1/bin/lab5-7_test [==[--gtest_filter=TSumTest.SimpleSum]==] --gtest_also_run_disabled_tests)
set_tests_properties( TSumTest.SimpleSum PROPERTIES WORKING_DIRECTORY /workspaces/labs_os-1/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TSumTest.InvalidInput /workspaces/labs_os-1/bin/lab5-7_test [==[--gtest_filter=TSumTest.InvalidInput]==] --gtest_also_run_disabled_tests)
set_tests_properties( TSumTest.InvalidInput PROPERTIES WORKING_DIRECTORY /workspaces/labs_os-1/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TPingTest.PingAll /workspaces/labs_os-1/bin/lab5-7_test [==[--gtest_filter=TPingTest.PingAll]==] --gtest_also_run_disabled_tests)
set_tests_properties( TPingTest.PingAll PROPERTIES WORKING_DIRECTORY /workspaces/labs_os-1/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TPingTest.NodeUnavailable /workspaces/labs_os-1/bin/lab5-7_test [==[--gtest_filter=TPingTest.NodeUnavailable]==] --gtest_also_run_disabled_tests)
set_tests_properties( TPingTest.NodeUnavailable PROPERTIES WORKING_DIRECTORY /workspaces/labs_os-1/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set( lab5-7_test_TESTS TTopologyTest.AddNode TTopologyTest.AddDuplicateNode TTopologyTest.RemoveNode TTopologyTest.GetChildren TSumTest.SimpleSum TSumTest.InvalidInput TPingTest.PingAll TPingTest.NodeUnavailable)
